const Ziggy = {
    url: 'https:\/\/pcaview.abc',
    port: null,
    defaults: {},
    routes: {
        home: { uri: '\/', methods: ['GET', 'HEAD'] },
        'symlink.track': { uri: 'symlink', methods: ['GET', 'HEAD'] },
        'church.home': {
            uri: 'c\/{church}',
            methods: ['GET', 'HEAD'],
            parameters: ['church'],
            bindings: { church: 'slug' },
        },
        church: { uri: 'church', methods: ['GET', 'HEAD'] },
        'church.show': { uri: 'church\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        department: { uri: 'department', methods: ['GET', 'HEAD'] },
        'department.show': {
            uri: 'department\/{id}',
            methods: ['GET', 'HEAD'],
            wheres: { id: '[0-9]+' },
            parameters: ['id'],
        },
        'department.keyword': { uri: 'department\/{keyword}', methods: ['GET', 'HEAD'], parameters: ['keyword'] },
        profile: { uri: 'profile', methods: ['GET', 'HEAD'] },
        'profile.subscribe': { uri: 'profile\/subscribe', methods: ['POST'] },
        'profile.photo.update': { uri: 'profile\/photo', methods: ['POST'] },
        'profile.delete': { uri: 'profile\/delete', methods: ['POST'] },
        dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
        'contents.show': { uri: 'contents\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'contents.destroy': { uri: 'contents\/{id}\/delete', methods: ['POST'], parameters: ['id'] },
        'mobile.home': { uri: 'm', methods: ['GET', 'HEAD'] },
        'mobile.church.home': {
            uri: 'm\/c\/{church}',
            methods: ['GET', 'HEAD'],
            parameters: ['church'],
            bindings: { church: 'slug' },
        },
        'mobile.church.show': { uri: 'm\/church\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'mobile.department.show': {
            uri: 'm\/department\/{id}',
            methods: ['GET', 'HEAD'],
            wheres: { id: '[0-9]+' },
            parameters: ['id'],
        },
        'mobile.contents.show': { uri: 'm\/contents\/{id}', methods: ['GET', 'HEAD'], parameters: ['id'] },
        'comments.store': {
            uri: 'contents\/{content}\/comments',
            methods: ['POST'],
            parameters: ['content'],
            bindings: { content: 'id' },
        },
        'comments.destroy': {
            uri: 'comments\/{comment}',
            methods: ['DELETE'],
            parameters: ['comment'],
            bindings: { comment: 'id' },
        },
        'feed.store': { uri: 'feed', methods: ['POST'] },
        'privacy-policy': { uri: 'privacy-policy', methods: ['GET', 'HEAD'] },
        'api.gold.latest': { uri: 'api\/gold\/latest', methods: ['GET', 'HEAD'] },
        'api.gold.history': { uri: 'api\/gold\/history', methods: ['GET', 'HEAD'] },
        'api.gold.statistics': { uri: 'api\/gold\/statistics', methods: ['GET', 'HEAD'] },
        'profile.edit': { uri: 'settings\/profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'settings\/profile', methods: ['PATCH'] },
        'profile.destroy': { uri: 'settings\/profile', methods: ['DELETE'] },
        'password.edit': { uri: 'settings\/password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'settings\/password', methods: ['PUT'] },
        'kakao.redirect': { uri: 'auth\/kakao', methods: ['GET', 'HEAD'] },
        'kakao.callback': { uri: 'auth\/kakao\/callback', methods: ['GET', 'HEAD'] },
        register: { uri: 'register', methods: ['GET', 'HEAD'] },
        'register.store': { uri: 'register', methods: ['POST'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'login.store': { uri: 'login', methods: ['POST'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password\/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': {
            uri: 'verify-email\/{id}\/{hash}',
            methods: ['GET', 'HEAD'],
            parameters: ['id', 'hash'],
        },
        'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        'password.confirm.store': { uri: 'confirm-password', methods: ['POST'] },
        logout: { uri: 'logout', methods: ['POST'] },
        'admin.departments.index': { uri: 'admin\/departments', methods: ['GET', 'HEAD'] },
        'admin.departments.edit': {
            uri: 'admin\/departments\/{department}\/edit',
            methods: ['GET', 'HEAD'],
            parameters: ['department'],
            bindings: { department: 'id' },
        },
        'admin.departments.update': {
            uri: 'admin\/departments\/{department}',
            methods: ['PUT'],
            parameters: ['department'],
            bindings: { department: 'id' },
        },
        'admin.churches.index': { uri: 'admin\/churches', methods: ['GET', 'HEAD'] },
        'admin.churches.edit': {
            uri: 'admin\/churches\/{church}\/edit',
            methods: ['GET', 'HEAD'],
            parameters: ['church'],
            bindings: { church: 'slug' },
        },
        'admin.churches.update': {
            uri: 'admin\/churches\/{church}',
            methods: ['PUT'],
            parameters: ['church'],
            bindings: { church: 'slug' },
        },
        sitemap: { uri: 'sitemap.xml', methods: ['GET', 'HEAD'] },
        'storage.local': {
            uri: 'storage\/{path}',
            methods: ['GET', 'HEAD'],
            wheres: { path: '.*' },
            parameters: ['path'],
        },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
